name: Update Submodules

on:
  push:
    branches:
      - main 
  repository_dispatch:
    types: [update-submodules]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Set up Git identity
      run: |
        git config --global user.email "wasath.vt@gmail.com"
        git config --global user.name "WasathTheekshana"
        
    - name: Update submodules
      run: |
        git submodule update --remote --recursive
        git add .
        
        # Check if there are changes in submodules
        submodule_changes=$(git status --porcelain | grep '^ M' | wc -l)
        if [ $submodule_changes -eq 0 ]; then
          echo "No changes in submodules."
        else
          export GIT_AUTHOR_DATE="2024-02-10T12:00:00"
          export GIT_COMMITTER_DATE="2024-02-10T12:00:00"
          if git commit -m "Update submodules" --date="2024-02-10T12:00:00"; then
            git config --global credential.helper 'store --file ~/.git-credentials'
            echo "https://github.com/Dune-Global/unite-deployment.git:${ACCESS_TOKEN}" > ~/.git-credentials
            git push https://github.com/Dune-Global/unite-deployment.git HEAD:main
          else
            echo "Failed to commit changes."
            exit 1
          fi
        fi
