name: Update Submodules

on:
  push:
    branches:
      - main  # Change this to match your default branch

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Update submodules
      run: |
        git submodule update --remote --recursive
        git add .
        export GIT_AUTHOR_DATE="2024-02-10T12:00:00"
        export GIT_COMMITTER_DATE="2024-02-10T12:00:00"
        git commit -m "Update submodules" --date="2024-02-10T12:00:00"
        git push
