name: Update Submodules

on:
  push:
    branches:
      - main 
  repository_dispatch:
    types: [update-submodules]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - name: Set up Git identity
        run: |
          git config --global user.email "wasath.vt@gmail.com"
          git config --global user.name "WasathTheekshana"
          
      - name: Update submodules
        run: |
          git fetch
          git submodule update --remote
          git submodule update --remote --merge
          git commit -am "Updated submodules"
          git push https://github.com/${{ github.repository }}.git HEAD:main
